# Generated by Django 4.1 on 2022-08-18 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.FloatField(max_length=3)),
                ('horario', models.DateTimeField(default=datetime.datetime(2022, 8, 17, 21, 58, 41, 141538))),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard_teste.animal')),
            ],
        ),
    ]
